### ISSUE TITLE
Ideas for future todo

### ISSUE THREAD

**Issue by jimmychu0807** [jimmychu0807/substrate-offchain-worker-demo#11]
- [ ] Refactored your pallet and separate the node out
- [ ] Switch `ValidateUnsigned` over to `SignedExtension`
- [ ] Write tests
- [ ] Make a 3-node setup: 1 node fetches from endpoint-X, another from endpoint-Y, and the third node as a medianizer.
- [ ] Gav: a price feed for kusama
- [ ] Gav: use transactions signed with the session key. Should not use "standard" signed transactions as then validators would need a hot account. (this is technically an UnsignedTransaction, but with a payload signed with session key)
- [ ] Gav: only allow validators to submit price
- [ ] Gav: only reward validators for the price when they're close to the median; slash validators when they're far off.
- [ ] blockFetch duration / remote endpoints all stored in storage and be updated on the fly, and managed via governance.
